### ISSUE TITLE
GroovyCastException on custom component in Vaadin 19

### ISSUE THREAD

**Issue by DarioArena87** [mvysny/vaadin-groovy-builder#2]
Hi i followed the examples to create two custom components DSL: One is an autocomplete (https://vaadin.com/directory/component/autocomplete) and it works, the other is using autocomplete to make a search in google maps with a debounce of 2 seconds.
The latter extends GComposite and when i try to instantiate it i get a GroovyCastException between the component's class and itself:

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'test.views.custom.GoogleMapsSearch@65724800' with class 'test.views.custom.GoogleMapsSearch' to class 'test.views.custom.GoogleMapsSearch'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405) ~[groovy-3.0.8.jar:3.0.8]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319) ~[groovy-3.0.8.jar:3.0.8]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:243) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2858) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3885) ~[groovy-3.0.8.jar:3.0.8]
	at com.github.mvysny.vaadingroovybuilder.v14.GComposite.setProperty(GComposite.groovy) ~[vaadin-groovy-builder-v14-0.0.8.jar:na]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:544) ~[groovy-3.0.8.jar:3.0.8]
	at com.github.mvysny.vaadingroovybuilder.v14.GComposite.this$dist$set$3(GComposite.groovy) ~[vaadin-groovy-builder-v14-0.0.8.jar:na]
	at com.github.mvysny.vaadingroovybuilder.v14.GComposite$1.propertyMissing(GComposite.groovy) ~[vaadin-groovy-builder-v14-0.0.8.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:883) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2895) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3885) ~[groovy-3.0.8.jar:3.0.8]
	at com.github.mvysny.vaadingroovybuilder.v14.GComposite$1.setProperty(GComposite.groovy) ~[vaadin-groovy-builder-v14-0.0.8.jar:na]
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyTryThese(Closure.java:377) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:367) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setProperty(Closure.java:348) ~[groovy-3.0.8.jar:3.0.8]
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyTryThese(Closure.java:382) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:367) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setProperty(Closure.java:348) ~[groovy-3.0.8.jar:3.0.8]
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:217) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyTryThese(Closure.java:382) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:367) ~[groovy-3.0.8.jar:3.0.8]
	at groovy.lang.Closure.setProperty(Closure.java:348) ~[groovy-3.0.8.jar:3.0.8]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:544) ~[groovy-3.0.8.jar:3.0.8]
	at test.views.View$_closure1$_closure2$_closure5.doCall(View.groovy:97) ~[classes/:na]
```

VaadinExtensions.groovy (extension methods):

```groovy
class VaadinExtensions {

    static Autocomplete autocomplete(HasComponents self, int limit,
         @DelegatesTo(value = Autocomplete, strategy = Closure.DELEGATE_FIRST) @NotNull Closure block) {
        VaadinDsl.init(self, new Autocomplete(limit), block)
    }
    
    static GoogleMapsSearch googleMapsSearch(HasComponents self,
         @DelegatesTo(value = GoogleMapsSearch, strategy = Closure.DELEGATE_FIRST) @NotNull Closure block) {
        VaadinDsl.init(self, new GoogleMapsSearch(), block)
    }
}
```

GoogleMapsSearch.groovy

```groovy
class GoogleMapsSearch extends GComposite {
    
    private Autocomplete autocomplete
    private Flux<String> userInputs
    
    private Map<String, GeocodingResult> tempResults
    
    private GeocodingResult selectedAddress
    
    private final root = ui {
        horizontalLayout {
            autocomplete = autocomplete(5) {
                label = 'Indirizzo'
        
                userInputs = Flux.create { emitter ->
                    addChangeListener {
                        emitter.next(it.value)
                    }
                }
        
                addAutocompleteValueAppliedListener {
                    selectedAddress = tempResults[it.value]
                }
        
                addValueClearListener {
                    selectedAddress = null
                }
            }
        }
    }
    
    GoogleMapsSearch() {
        userInputs
        .sampleTimeout { Mono.delay(Duration.ofSeconds(2)) }
        .filter { it.length() > 4 }
        .flatMap { Services.get(GoogleMaps).search(it) }
        .subscribe {
            tempResults = it.collectEntries {[it.formattedAddress, it] }
            onUI {
                autocomplete.options = tempResults.keySet().toList()
            }
        }
    }
}
```

View.groovy
```groovy
@Route(layout = MainView)
@PageTitle("View")
class View extends GComposite {
    ...
    private GoogleMapsSearch searchAddress
    ...
    def root = ui {
        div {
        ...
            formLayout {
                ...
                searchAddress = googleMapsSearch {}
            }
        }
    }

}
```

I have verified that there are not two different classes on the classpath with the same fully qualified name, am i doing something else wrong?
Here is my current setup:
vaadin version: 19.0.7
target java version: 1.8
jvm: openjdk 11.0.11 2021-04-20
groovy version: 3.0.8

**Comment by mvysny** [comment]
This kind of weird issues usually happen when there are multiple classloaders in use; a class loaded by classloader A can not be cast to the class with the same class name but loaded by classloader B.

Hmm. Let me rework the example project at https://github.com/mvysny/vaadin-groovy-builder/tree/master/example to use GComposite+DSL for the Toolbar and try it for myself.

Also try to use `@CompileStatic` - maybe the `googleMapsSearch` extension function hasn't been resolved properly and Groovy is simply doing some dynamic weird stuff. Also Groovy can't both declare and use DSLs in one project - you'll need to move components+DSL to one Gradle project, and your app to another.

Or use Kotlin :-D

**Comment by mvysny** [comment]
I've now modified the example app to export a component Toolbar via a DSL and also consume it. Seems to be working for me. If it still fails for you, can you please create an example app which reproduces the issue, then attach the app with sources as a zip here?

**Comment by DarioArena87** [comment]
I think you are right, for some strange reason it seems that vaadin UI classes are loaded by the bootstrap (null) classloader and other groovy classes like extension method's wrappers and custom components are loaded by the application classloader.
I have made some println of each class' classloader name and these are the results:

```
Classloader of View: null
Classloader of GoogleMapsSearch: app
Classloader of VaadinExtensions: app
```

I'm trying to make a super small application just to reproduce the issue and attach to this issue. I don't have much free time right now but i'll try my best.

**Comment by DarioArena87** [comment]
I think i managed to pin down the issue: it is caused by using spring boot dev tools that uses a custom classloader to reload Vaadin views when there are some changes. I temporarily removed the dev-tools dependency from the pom.xml and the problem went away because now both the view and the custom component uses the same classloader:

```
Classloader of View: app
Classloader of GoogleMapsSearch: app
```
I don't really know if it is an issue in how i have configured the project (that is pretty standard) or if it is a weird bug due to how dev-tools messes up groovy extension methods (maybe it is a problem in groovy itself!)
If there is a known workaround that i'm not aware of i can try to see if it works but for now i can just leave dev-tools out and don't use it.

**Comment by mvysny** [comment]
Hi, excellent work hunting down that bug! If I understand correctly, turning off Spring dev tools makes the project work correctly.

If I would have to guess, I'd guess the culprit to be either Groovy, Spring dev-tools, or the combination of those two. I wouldn't personally guess extension methods since they get compiled to static methods which is a pretty basic JVM stuff which should definitely work.

Unfortunately I'm not aware of any workaround. Perhaps the best way to proceed is to ask on Spring Forums or StackOverflow, to see whether someone else encountered this kind of issue as well.

**Comment by mvysny** [comment]
Closing as inactive; please feel free to reopen & add more information if need be.
